## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [4]:
%pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ---------------------------------------- 0.0/250.9 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.9 kB ? eta -:--:--
   ------ -------------------------------- 41.0/250.9 kB 487.6 kB/s eta 0:00:01
   ---------------------------------------  245.8/250.9 kB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 250.9/250.9 kB 2.2 MB/s eta 0:00:00
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
df = pd.read_excel("D:/Placement Smvitm/aids_attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW23AD50,SRAJAN S,Data Science & GenAI - 3nd Yr- AI&DS,11,0,11,0,0%,Critical,33 more,Never,11
1,4MW24AD001,ADITHYA S POOJARY,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0,64%,Critical,5 more,2026-10-07,0
2,4MW24AD002,ANKITHA PRASANNA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0,100%,Safe,✓ Met,2026-10-07,0
3,4MW24AD003,ANUSHA KOTEGAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
4,4MW24AD004,ANVITA RAMESH NAIK,Data Science & GenAI - 3nd Yr- AI&DS,11,9,2,0,82%,Warning,✓ Met,2026-10-07,0
...,...,...,...,...,...,...,...,...,...,...,...,...
57,4MW24AD059,ZEHA AYESHA,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,90%,Safe,✓ Met,2026-10-07,0
58,4MW24AD060,AMITH G PALANDYE,Data Science & GenAI - 3nd Yr- AI&DS,10,0,10,0,0%,Critical,30 more,Never,10
59,4MW24AD061,AMOGH BHASKAR NAIK,Data Science & GenAI - 3nd Yr- AI&DS,10,5,5,0,50%,Critical,10 more,2026-10-07,0
60,4MW24AD062,CHANDISH,Data Science & GenAI - 3nd Yr- AI&DS,10,6,4,0,60%,Critical,6 more,2026-10-05,1
61,4MW25AD400,SAMPATH S HEBBAR,Data Science & GenAI - 3nd Yr- AI&DS,10,1,9,0,10%,Critical,26 more,2026-09-02,8

#### Section 1: Data Inspection

In [ ]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------

In [6]:
# Display the first 10 rows
display(df.head(10))

# Display the shape of the DataFrame
print("Shape of the DataFrame:", df.shape)

# Display the data types of each column
print("\nData types of each column:")
print(df.dtypes)

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW23AD50,SRAJAN S,Data Science & GenAI - 3nd Yr- AI&DS,11,0,11,0,0%,Critical,33 more,Never,11
1,4MW24AD001,ADITHYA S POOJARY,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0,64%,Critical,5 more,2026-10-07,0
2,4MW24AD002,ANKITHA PRASANNA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0,100%,Safe,✓ Met,2026-10-07,0
3,4MW24AD003,ANUSHA KOTEGAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
4,4MW24AD004,ANVITA RAMESH NAIK,Data Science & GenAI - 3nd Yr- AI&DS,11,9,2,0,82%,Warning,✓ Met,2026-10-07,0
5,4MW24AD005,ARPITHA M THANTRY,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73%,Critical,1 more,2026-10-07,0
6,4MW24AD007,ASNIYA,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
7,4MW24AD008,B. G PRARTHANA HEBBAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
8,4MW24AD009,BHARATHRAJ A NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,4,7,0,36%,Critical,17 more,2026-10-05,1
9,4MW24AD010,BHEEMA KATTIMANI,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73%,Critical,1 more,2026-10-07,0

Shape of the DataFrame: (62, 12)

Data types of each column:
Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [ ]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
#-----------------------------Write Solution Code-----------------------------

In [7]:
# 1. Check null/missing values in each column
null_counts = df.isnull().sum()
print("Missing values count per column:")
print(null_counts)

# 2. Count occurrences where "Last Present Date" is explicitly marked as "Never"
if 'Last Present Date' in df.columns:
    never_count = (df['Last Present Date'].astype(str).str.strip().str.lower() == 'never').sum()
    print(f"\nNumber of 'Never' entries in 'Last Present Date': {never_count}")

# 3. Summary of columns that contain missing values
print("\nColumns with missing (NaN/null) values:")
print(null_counts[null_counts > 0])

Missing values count per column:
Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64

Number of 'Never' entries in 'Last Present Date': 5

Columns with missing (NaN/null) values:
Series([], dtype: int64)

In [ ]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
#-----------------------------Write Solution Code-----------------------------

In [8]:
# Rename columns by converting to lowercase, replacing spaces and special characters with underscores
df.columns = (
    df.columns.str.strip()
    .str.lower()
    .str.replace('%', 'pct', regex=False)
    .str.replace(r'[^a-z0-9_]', '_', regex=True)
    .str.replace(r'_+', '_', regex=True)
    .str.strip('_')
)

# Display the updated column list
print("Updated columns:")
print(df.columns.tolist())

Updated columns:
['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75pct', 'last_present_date', 'consecutive_absences']

In [ ]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code-----------------------------

In [9]:
# 1. Convert attendance_pct to numeric float
if df['attendance_pct'].dtype == 'object':
    df['attendance_pct'] = (
        df['attendance_pct']
        .astype(str)
        .str.rstrip('%')
        .astype(float)
    )

# 2. Convert last_present_date to datetime, treating 'Never' (and invalid entries) as NaT
df['last_present_date'] = pd.to_datetime(
    df['last_present_date'].replace('Never', None), 
    errors='coerce'
)

# Display data types and sample rows to verify
print(df[['attendance_pct', 'last_present_date']].dtypes)
df[['attendance_pct', 'last_present_date']].head()

attendance_pct                  str
last_present_date    datetime64[us]
dtype: object

  attendance_pct last_present_date
0             0%               NaT
1            64%        2026-10-07
2           100%        2026-10-07
3            91%        2026-10-07
4            82%        2026-10-07

#### Section 2: Filtering & Selection

In [ ]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------

In [10]:
# Filter for "Critical" status and sort by attendance_pct in ascending order
critical_students = (
    df[df['status'].str.lower() == 'critical']
    .sort_values(by='attendance_pct', ascending=True)
)

# Display the result
display(critical_students)

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences
0,4MW23AD50,SRAJAN S,Data Science & GenAI - 3nd Yr- AI&DS,11,0,11,0,0%,Critical,33 more,NaT,11
58,4MW24AD060,AMITH G PALANDYE,Data Science & GenAI - 3nd Yr- AI&DS,10,0,10,0,0%,Critical,30 more,NaT,10
52,4MW24AD054,UJWAL. K,Data Science & GenAI - 3nd Yr- AI&DS,10,0,10,0,0%,Critical,30 more,NaT,10
45,4MW24AD046,SHARANU PATIL,Data Science & GenAI - 3nd Yr- AI&DS,10,0,10,0,0%,Critical,30 more,NaT,10
36,4MW24AD037,RISHAN FRANCIS MENEZES,Data Science & GenAI - 3nd Yr- AI&DS,10,0,10,0,0%,Critical,30 more,NaT,10
61,4MW25AD400,SAMPATH S HEBBAR,Data Science & GenAI - 3nd Yr- AI&DS,10,1,9,0,10%,Critical,26 more,2026-09-02,8
26,4MW24AD027,PRAJWAL,Data Science & GenAI - 3nd Yr- AI&DS,11,3,8,0,27%,Critical,21 more,2026-10-05,1
30,4MW24AD031,PRAVEEN KUMAR N,Data Science & GenAI - 3nd Yr- AI&DS,10,3,7,0,30%,Critical,18 more,2026-10-07,0
8,4MW24AD009,BHARATHRAJ A NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,4,7,0,36%,Critical,17 more,2026-10-05,1
31,4MW24AD032,PREETH SHETTY,Data Science & GenAI - 3nd Yr- AI&DS,10,5,5,0,50%,Critical,10 more,2026-10-05,1
37,4MW24AD038,RITHESH R,Data Science & GenAI - 3nd Yr- AI&DS,10,5,5,0,50%,Critical,10 more,2026-10-05,1
59,4MW24AD061,AMOGH BHASKAR NAIK,Data Science & GenAI - 3nd Yr- AI&DS,10,5,5,0,50%,Critical,10 more,2026-10-07,0
10,4MW24AD011,BINDU,Data Science & GenAI - 3nd Yr- AI&DS,11,6,5,0,55%,Critical,9 more,2026-10-07,0
41,4MW24AD042,SANJAN SHETTY,Data Science & GenAI - 3nd Yr- AI&DS,10,6,4,0,60%,Critical,6 more,2026-10-05,1
55,4MW24AD057,VIGHNESH,Data Science & GenAI - 3nd Yr- AI&DS,10,6,4,0,60%,Critical,6 more,2026-10-07,0
60,4MW24AD062,CHANDISH,Data Science & GenAI - 3nd Yr- AI&DS,10,6,4,0,60%,Critical,6 more,2026-10-05,1
17,4MW24AD018,MANISH THINGALAYA,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0,64%,Critical,5 more,2026-10-07,0
18,4MW24AD019,MOHAMMED SUHAN,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0,64%,Critical,5 more,2026-10-07,0
19,4MW24AD020,MOHAMMED AFREED,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0,64%,Critical,5 more,2026-10-07,0
1,4MW24AD001,ADITHYA S POOJARY,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0,64%,Critical,5 more,2026-10-07,0
23,4MW24AD024,NISHANTH SHETTY,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0,64%,Critical,5 more,2026-10-07,0
13,4MW24AD014,GOURISH VENKATRAMAN MOGER,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0,64%,Critical,5 more,2026-10-07,0
56,4MW24AD058,ZEENATH ZIYAN,Data Science & GenAI - 3nd Yr- AI&DS,10,7,3,0,70%,Critical,2 more,2026-10-07,0
40,4MW24AD041,SAMANA G RAO,Data Science & GenAI - 3nd Yr- AI&DS,10,7,3,0,70%,Critical,2 more,2026-10-07,0
5,4MW24AD005,ARPITHA M THANTRY,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73%,Critical,1 more,2026-10-07,0
11,4MW24AD012,CHIRAG N KUNDER,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73%,Critical,1 more,2026-10-07,0
25,4MW24AD026,PAVAN S POOJARY,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73%,Critical,1 more,2026-10-07,0
21,4MW24AD022,MONISHA DEVADIGA,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73%,Critical,1 more,2026-10-07,0
20,4MW24AD021,MOHAMMED AWAD TONSE,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73%,Critical,1 more,2026-10-07,0
16,4MW24AD017,KISHAN GANAPATI HEGDE,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73%,Critical,1 more,2026-10-07,0
9,4MW24AD010,BHEEMA KATTIMANI,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73%,Critical,1 more,2026-10-07,0
24,4MW24AD025,PAVAN BHAT,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73%,Critical,1 more,2026-10-07,0

In [ ]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------

In [11]:
# Filter students with 0 present days (or total_present == 0)
fully_absent = df.loc[
    df['present'] == 0,
    ['roll_no', 'student_name', 'consecutive_absences']
]

# Display the resulting DataFrame
display(fully_absent)

       roll_no            student_name  consecutive_absences
0    4MW23AD50               SRAJAN  S                    11
36  4MW24AD037  RISHAN FRANCIS MENEZES                    10
45  4MW24AD046           SHARANU PATIL                    10
52  4MW24AD054                UJWAL. K                    10
58  4MW24AD060        AMITH G PALANDYE                    10

In [ ]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------

In [12]:
# (a) Display all "Safe" students using .loc
safe_students = df.loc[df['status'].str.lower() == 'safe']
print("--- (a) Safe Students (.loc) ---")
display(safe_students)

# (b) Display the first 15 rows and columns 2-6 (indices 1 to 5) using .iloc
first_15_cols_2_to_6 = df.iloc[0:15, 1:6]
print("\n--- (b) First 15 Rows, Columns 2-6 (.iloc) ---")
display(first_15_cols_2_to_6)

--- (a) Safe Students (.loc) ---

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences
2,4MW24AD002,ANKITHA PRASANNA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0,100%,Safe,✓ Met,2026-10-07,0
3,4MW24AD003,ANUSHA KOTEGAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
6,4MW24AD007,ASNIYA,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
7,4MW24AD008,B. G PRARTHANA HEBBAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
14,4MW24AD015,K MANYA RAO,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91%,Safe,✓ Met,2026-10-07,0
15,4MW24AD016,KAVYA,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0,100%,Safe,✓ Met,2026-10-07,0
28,4MW24AD029,PRATHEEKSHA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0,100%,Safe,✓ Met,2026-10-07,0
32,4MW24AD033,PRIYADARSHINI,Data Science & GenAI - 3nd Yr- AI&DS,10,10,0,0,100%,Safe,✓ Met,2026-10-07,0
33,4MW24AD034,RAKSHITHA (ASHOK KUMAR),Data Science & GenAI - 3nd Yr- AI&DS,10,10,0,0,100%,Safe,✓ Met,2026-10-07,0
35,4MW24AD036,RAMITHA R RAO,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,90%,Safe,✓ Met,2026-10-07,0
39,4MW24AD040,SAKSHI,Data Science & GenAI - 3nd Yr- AI&DS,10,10,0,0,100%,Safe,✓ Met,2026-10-07,0
42,4MW24AD043,SANJANA A MOOLYA,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,90%,Safe,✓ Met,2026-10-05,1
43,4MW24AD044,SANVI SHETTIGAR,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,90%,Safe,✓ Met,2026-10-07,0
44,4MW24AD045,SHARADHI,Data Science & GenAI - 3nd Yr- AI&DS,10,10,0,0,100%,Safe,✓ Met,2026-10-07,0
46,4MW24AD047,SHETTY RAKSHA UDAY,Data Science & GenAI - 3nd Yr- AI&DS,10,10,0,0,100%,Safe,✓ Met,2026-10-07,0
47,4MW24AD048,SHRADDHA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,10,10,0,0,100%,Safe,✓ Met,2026-10-07,0
48,4MW24AD049,SHRAVYA,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,90%,Safe,✓ Met,2026-10-05,1
49,4MW24AD050,SHRI RAKSHA BHAT,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,90%,Safe,✓ Met,2026-10-07,0
50,4MW24AD052,TASMIYA ANJUM,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,90%,Safe,✓ Met,2026-10-07,0
51,4MW24AD053,THRISHA,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,90%,Safe,✓ Met,2026-10-07,0
53,4MW24AD055,VAISHNAVI K AMIN,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,90%,Safe,✓ Met,2026-10-07,0
54,4MW24AD056,VANDANA V DEVADIGA,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,90%,Safe,✓ Met,2026-10-07,0
57,4MW24AD059,ZEHA AYESHA,Data Science & GenAI - 3nd Yr- AI&DS,10,9,1,0,90%,Safe,✓ Met,2026-10-07,0

--- (b) First 15 Rows, Columns 2-6 (.iloc) ---

,student_name,subject,total_classes,present,absent
0,SRAJAN S,Data Science & GenAI - 3nd Yr- AI&DS,11,0,11
1,ADITHYA S POOJARY,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4
2,ANKITHA PRASANNA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0
3,ANUSHA KOTEGAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1
4,ANVITA RAMESH NAIK,Data Science & GenAI - 3nd Yr- AI&DS,11,9,2
5,ARPITHA M THANTRY,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3
6,ASNIYA,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1
7,B. G PRARTHANA HEBBAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1
8,BHARATHRAJ A NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,4,7
9,BHEEMA KATTIMANI,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3
10,BINDU,Data Science & GenAI - 3nd Yr- AI&DS,11,6,5
11,CHIRAG N KUNDER,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3
12,DHANYA,Data Science & GenAI - 3nd Yr- AI&DS,11,9,2
13,GOURISH VENKATRAMAN MOGER,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4
14,K MANYA RAO,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1

In [ ]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------

In [13]:
# Filter students with 5 or more consecutive absences and select specific columns
consecutive_absent_students = df.loc[
    df['consecutive_absences'] >= 5, 
    ['student_name', 'status', 'last_present_date']
]

# Display the result
display(consecutive_absent_students)

              student_name    status last_present_date
0                SRAJAN  S  Critical               NaT
36  RISHAN FRANCIS MENEZES  Critical               NaT
45           SHARANU PATIL  Critical               NaT
52                UJWAL. K  Critical               NaT
58        AMITH G PALANDYE  Critical               NaT
61        SAMPATH S HEBBAR  Critical        2026-09-02

### Section 3: Grouping & Aggregation

In [ ]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------

In [15]:
# Group by 'status' and aggregate count, mean attendance_pct, and max consecutive_absences
# Convert percentage strings (for example, "64%") to numbers before calculating the mean
df['attendance_pct'] = pd.to_numeric(
    df['attendance_pct'].astype(str).str.rstrip('%'),
    errors='coerce'
)

status_summary = df.groupby('status').agg(
    student_count=('student_name', 'count'),
    avg_attendance_pct=('attendance_pct', 'mean'),
    max_consecutive_absences=('consecutive_absences', 'max')
).reset_index()

# Display the summary table
display(status_summary)

     status  student_count  avg_attendance_pct  max_consecutive_absences
0  Critical             32           49.875000                        11
1      Safe             23           94.086957                         1
2   Warning              7           81.428571                         1

In [ ]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------

In [16]:
import numpy as np

# 1. Define conditions and choices for the category assignment
conditions = [
    df['attendance_pct'] >= 90,
    (df['attendance_pct'] >= 75) & (df['attendance_pct'] < 90),
    (df['attendance_pct'] >= 60) & (df['attendance_pct'] < 75),
    df['attendance_pct'] < 60
]

choices = ['Excellent', 'Good', 'Average', 'Poor']

# 2. Create the 'attendance_category' column using np.select
df['attendance_category'] = np.select(conditions, choices, default='Unknown')

# 3. Group by 'attendance_category' and count the number of students
category_counts = (
    df.groupby('attendance_category')
    .size()
    .reset_index(name='student_count')
)

# Display the category counts
display(category_counts)

  attendance_category  student_count
0             Average             19
1           Excellent             23
2                Good              7
3                Poor             13

In [ ]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------

In [17]:
print(df.columns.tolist())

['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75pct', 'last_present_date', 'consecutive_absences', 'attendance_category']

In [19]:
# Calculate total classes conducted, total present, and total absent across all students
# Calculate total classes conducted, total present, and total absent across all students
overall_totals = df[['total_classes', 'present', 'absent']].sum()

print("Overall Totals Across All Students:")
print(overall_totals)

Overall Totals Across All Students:
total_classes    650
present          454
absent           196
dtype: int64

In [ ]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------

In [20]:
# Select the appropriate present/absent columns dynamically based on existing dataframe columns
present_col = 'total_present' if 'total_present' in df.columns else 'present'
absent_col = 'total_absent' if 'total_absent' in df.columns else 'absent'

# Group by status and calculate requested aggregations
status_agg = df.groupby('status').agg(
    min_present=(present_col, 'min'),
    max_present=(present_col, 'max'),
    mean_present=(present_col, 'mean'),
    sum_absent=(absent_col, 'sum')
).reset_index()

# Display results
display(status_agg)

     status  min_present  max_present  mean_present  sum_absent
0  Critical            0            8      5.312500         168
1      Safe            9           11      9.695652          14
2   Warning            8            9      8.714286          14

### Section 4: Feature Engineering & Transformation

In [ ]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------

In [21]:
# Identify column names for absent and consecutive absences dynamically
absent_col = 'total_absent' if 'total_absent' in df.columns else 'absent'
consecutive_col = 'consecutive_absences' if 'consecutive_absences' in df.columns else 'consecutive_absent'

# Calculate Risk Score: (Absent * 0.4) + (Consecutive Absences * 0.6)
df['risk_score'] = (df[absent_col] * 0.4) + (df[consecutive_col] * 0.6)

# Display top 10 students with the highest risk score
top_10_risk = (
    df[['roll_no', 'student_name', absent_col, consecutive_col, 'risk_score']]
    .sort_values(by='risk_score', ascending=False)
    .head(10)
)

display(top_10_risk)

,roll_no,student_name,absent,consecutive_absences,risk_score
0,4MW23AD50,SRAJAN S,11,11,11.0
36,4MW24AD037,RISHAN FRANCIS MENEZES,10,10,10.0
52,4MW24AD054,UJWAL. K,10,10,10.0
58,4MW24AD060,AMITH G PALANDYE,10,10,10.0
45,4MW24AD046,SHARANU PATIL,10,10,10.0
61,4MW25AD400,SAMPATH S HEBBAR,9,8,8.4
26,4MW24AD027,PRAJWAL,8,1,3.8
8,4MW24AD009,BHARATHRAJ A NAYAK,7,1,3.4
30,4MW24AD031,PRAVEEN KUMAR N,7,0,2.8
31,4MW24AD032,PREETH SHETTY,5,1,2.6

In [ ]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------

In [22]:
# Identify column name dynamically
col_75 = [c for c in df.columns if '75' in c][0]

# Extract numeric value or set to 0 for 'Met'
df['classes_needed_numeric'] = (
    df[col_75]
    .astype(str)
    .str.extract(r'(\d+)')
    .fillna(0)
    .astype(int)
)

# Display sample output
display(df[['student_name', col_75, 'classes_needed_numeric']].head(10))

C:\Temp\ipykernel_22464\2452454732.py:9: Pandas4Warning: 'int' is not supported as a fill value for str dtype. In a future version, calling fillna with an incompatible value will raise. Explicitly cast to a common dtype before filling.
  .fillna(0)

             student_name classes_needed_75pct  classes_needed_numeric
0               SRAJAN  S              33 more                      33
1       ADITHYA S POOJARY               5 more                       5
2  ANKITHA PRASANNA NAYAK                ✓ Met                       0
3          ANUSHA KOTEGAR                ✓ Met                       0
4      ANVITA RAMESH NAIK                ✓ Met                       0
5       ARPITHA M THANTRY               1 more                       1
6                  ASNIYA                ✓ Met                       0
7   B. G PRARTHANA HEBBAR                ✓ Met                       0
8      BHARATHRAJ A NAYAK              17 more                      17
9        BHEEMA KATTIMANI               1 more                       1

In [ ]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------

In [23]:
# Create Attendance Flag using apply with a lambda function
df['attendance_flag'] = df['attendance_pct'].apply(
    lambda x: "Defaulter" if x < 75 else "Safe"
)

# Display student name, attendance %, and the generated flag
display(df[['student_name', 'attendance_pct', 'attendance_flag']].head(10))

             student_name  attendance_pct attendance_flag
0               SRAJAN  S               0       Defaulter
1       ADITHYA S POOJARY              64       Defaulter
2  ANKITHA PRASANNA NAYAK             100            Safe
3          ANUSHA KOTEGAR              91            Safe
4      ANVITA RAMESH NAIK              82            Safe
5       ARPITHA M THANTRY              73       Defaulter
6                  ASNIYA              91            Safe
7   B. G PRARTHANA HEBBAR              91            Safe
8      BHARATHRAJ A NAYAK              36       Defaulter
9        BHEEMA KATTIMANI              73       Defaulter

In [ ]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------

In [24]:
# Bin attendance into defined ranges using pd.cut
bins = [0, 50, 75, 90, 100]
labels = ["Critical", "Warning", "Good", "Excellent"]

df['attendance_bin'] = pd.cut(
    df['attendance_pct'], 
    bins=bins, 
    labels=labels, 
    include_lowest=True
)

# Display student name, attendance %, and assigned bin
display(df[['student_name', 'attendance_pct', 'attendance_bin']].head(10))

             student_name  attendance_pct attendance_bin
0               SRAJAN  S               0       Critical
1       ADITHYA S POOJARY              64        Warning
2  ANKITHA PRASANNA NAYAK             100      Excellent
3          ANUSHA KOTEGAR              91      Excellent
4      ANVITA RAMESH NAIK              82           Good
5       ARPITHA M THANTRY              73        Warning
6                  ASNIYA              91      Excellent
7   B. G PRARTHANA HEBBAR              91      Excellent
8      BHARATHRAJ A NAYAK              36       Critical
9        BHEEMA KATTIMANI              73        Warning

### Section 5: Advanced Analysis

In [ ]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------

In [25]:
# Create a pivot table showing the count of students by Status and Attendance Category
pivot_summary = df.pivot_table(
    index='status', 
    columns='attendance_category', 
    values='student_name', 
    aggfunc='count', 
    fill_value=0
)

# Display the pivot table
display(pivot_summary)

attendance_category  Average  Excellent  Good  Poor
status
Critical                  19          0     0    13
Safe                       0         23     0     0
Warning                    0          0     7     0

In [ ]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------

In [26]:
# 1. Extract base name by stripping trailing numbers or extra whitespace
# Handles patterns like "ANANYA 1", "ANANYA 2", "DISHA 1", etc.
df['base_name'] = df['student_name'].str.replace(r'\s*\d+$', '', regex=True).str.strip()

# 2. Identify all rows where the base name is duplicated
duplicate_mask = df.duplicated(subset=['base_name'], keep=False)
duplicate_students = df[duplicate_mask].sort_values(by='base_name')

# Display the duplicate student rows
display(duplicate_students[['roll_no', 'student_name', 'base_name', 'status', 'attendance_pct']])

Empty DataFrame
Columns: [roll_no, student_name, base_name, status, attendance_pct]
Index: []

In [ ]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------

In [27]:
import pandas as pd

# Create hypothetical Student_Details DataFrame matching roll_no values in df
student_details = pd.DataFrame({
    'roll_no': df['roll_no'].unique(),
    'branch': ['AIDS'] * len(df['roll_no'].unique()),
    'semester': [4] * len(df['roll_no'].unique())
})

# Perform inner join on 'roll_no'
merged_df = pd.merge(df, student_details, on='roll_no', how='inner')

# Display the merged DataFrame
display(merged_df.head(10))

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75pct,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,attendance_flag,attendance_bin,base_name,branch,semester
0,4MW23AD50,SRAJAN S,Data Science & GenAI - 3nd Yr- AI&DS,11,0,11,0,0,Critical,33 more,NaT,11,Poor,11.0,33,Defaulter,Critical,SRAJAN S,AIDS,4
1,4MW24AD001,ADITHYA S POOJARY,Data Science & GenAI - 3nd Yr- AI&DS,11,7,4,0,64,Critical,5 more,2026-10-07,0,Average,1.6,5,Defaulter,Warning,ADITHYA S POOJARY,AIDS,4
2,4MW24AD002,ANKITHA PRASANNA NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,11,0,0,100,Safe,✓ Met,2026-10-07,0,Excellent,0.0,0,Safe,Excellent,ANKITHA PRASANNA NAYAK,AIDS,4
3,4MW24AD003,ANUSHA KOTEGAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91,Safe,✓ Met,2026-10-07,0,Excellent,0.4,0,Safe,Excellent,ANUSHA KOTEGAR,AIDS,4
4,4MW24AD004,ANVITA RAMESH NAIK,Data Science & GenAI - 3nd Yr- AI&DS,11,9,2,0,82,Warning,✓ Met,2026-10-07,0,Good,0.8,0,Safe,Good,ANVITA RAMESH NAIK,AIDS,4
5,4MW24AD005,ARPITHA M THANTRY,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73,Critical,1 more,2026-10-07,0,Average,1.2,1,Defaulter,Warning,ARPITHA M THANTRY,AIDS,4
6,4MW24AD007,ASNIYA,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91,Safe,✓ Met,2026-10-07,0,Excellent,0.4,0,Safe,Excellent,ASNIYA,AIDS,4
7,4MW24AD008,B. G PRARTHANA HEBBAR,Data Science & GenAI - 3nd Yr- AI&DS,11,10,1,0,91,Safe,✓ Met,2026-10-07,0,Excellent,0.4,0,Safe,Excellent,B. G PRARTHANA HEBBAR,AIDS,4
8,4MW24AD009,BHARATHRAJ A NAYAK,Data Science & GenAI - 3nd Yr- AI&DS,11,4,7,0,36,Critical,17 more,2026-10-05,1,Poor,3.4,17,Defaulter,Critical,BHARATHRAJ A NAYAK,AIDS,4
9,4MW24AD010,BHEEMA KATTIMANI,Data Science & GenAI - 3nd Yr- AI&DS,11,8,3,0,73,Critical,1 more,2026-10-07,0,Average,1.2,1,Defaulter,Warning,BHEEMA KATTIMANI,AIDS,4

In [ ]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------

In [28]:
# (a) Export all "Critical" students
df[df['status'].str.lower() == 'critical'].to_csv('critical_students.csv', index=False)

# (b) Export summary statistics grouped by Status
status_summary = df.groupby('status').agg(
    student_count=('student_name', 'count'),
    avg_attendance=('attendance_pct', 'mean'),
    max_consecutive_absences=('consecutive_absences', 'max')
)
status_summary.to_csv('status_summary_statistics.csv')

# (c) Export top 10 students by Risk Score
df.sort_values(by='risk_score', ascending=False).head(10).to_csv('top_10_risk_students.csv', index=False)

print("All 3 CSV files have been exported successfully!")

All 3 CSV files have been exported successfully!